site: Argon Jekyll Theme

url: https://naomimmg.github.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 6 # Or however many you want per page
  permalink: '/page/:num/'
  
